language: ruby

rvm:
  - 2.3.3

install:
  - bundle install
  - yarn

cache: yarn

script:
  - yarn coverage

before_deploy:
  - if [ "$TRAVIS_BRANCH" == "develop" ]; then bundle exec jekyll clean && bundle exec jekyll build; fi

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation
